### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by ghost** [jlengstorf/gatsby-tailwind-demo#10]
I tried to import this to my project to use tailwind css and it doesnt work 
is it still being maintained?

**Comment by ghost** [comment]
@jlengstorf do you have any instructions how I can use tailwind like this project in an existing project? thanks

**Comment by jlengstorf** [comment]
@LittleHamster I don't, unfortunately. This little demo is the extent of my experience with tailwind.

I'd recommend checking out [the Gatsby docs on Tailwind](https://www.gatsbyjs.org/docs/tailwind-css/) for more help.

Good luck!
