### ISSUE TITLE
Custom CSS - Develop Failing / Build is Fine

### ISSUE THREAD

**Issue by TomPichaud** [jlengstorf/gatsby-tailwind-demo#2]
Hello,

I ran into a strange issue, on development the custom css is not taking into account, so default tailwind css is being use.

On building / serve, the custom css is being use.

Is it Gatsby related ? or a config mistake ?

**Comment by jlengstorf** [comment]
@TomPichaud I'm honestly not sure. Do you have a repo so I can see a reproduction of the issue?

**Comment by TomPichaud** [comment]
I used this repo to reproduce the error, just change the purple color variable for example.

**Comment by jlengstorf** [comment]
Ah, okay. Let me take a look at that. I'm not all that familiar with how Tailwind works, so I didn't try to customize anything when I put this demo together.

**Comment by TomPichaud** [comment]
Thanks, I've tried to look into it, but to be honest I got lost for 2 hours... The fact that it is working in build should be Gatsby or Emotion related ? As tailwind is working properly.

**Comment by TomPichaud** [comment]
Hello, any progress ? or any advice to help resolve this issue ? Maybe if you guide or give me a process to follow I can try to have a look into it.

**Comment by TomPichaud** [comment]
Upgrading to --latest seems to resolve it.

**Comment by jlengstorf** [comment]
Hey, glad to hear that! Sorry I didn't get to this sooner. --

*Jason Lengstorf*
Get #deepinthecreep: *Twitter <https://twitter.com/jlengstorf>* · GitHub
<https://github.com/jlengstorf> · *LinkedIn
<https://linkedin.com/in/jlengstorf/>*
Oversharing at *lengstorf.com <https://lengstorf.com/>*

**Comment by TomPichaud** [comment]
Ok actually it wasn't fixed, I opened a new issue on Tailwind : https://github.com/tailwindcss/tailwindcss/issues/524 If you could please have a look, It would be nice to know who is to blame for this bug, Tailwind, Gatsby, postcss.... ? I think it's more likely to be Tailwind with the way they load the config.

**Comment by TomPichaud** [comment]
Hey, I'm sorry to disturb you again with this issue, 
https://github.com/tailwindcss/tailwindcss/issues/524, I still can't really make it work... Any help please?

**Comment by jlengstorf** [comment]
@TomPichaud So sorry for the delay here — I haven't had time to debug this, but @kylegalbraith has a blog post on using Tailwind with Gatsby: https://blog.kylegalbraith.com/2018/08/07/how-to-make-an-awesome-blog-using-gatsbyjs-and-aws/

He's got it working, so maybe I can convince him to take a look at what I set up wrong in this demo? (No worries if you don't have time, Kyle!)

**Comment by TomPichaud** [comment]
No worries, I’ll have a look tonight, and if I can’t sort it out, I’ll let you know. Thank you.
