### ISSUE TITLE
Tailwind Fraction values are not being compiled correctly

### ISSUE THREAD

**Issue by Praneeth-Pike** [jlengstorf/gatsby-tailwind-demo#5]
Hi, I not sure if I'm missing something, but when I try to use the fraction tailwind classes like w-1/2, w-1/3, the compiled values are only for w-1

For example:
` ${tw`w-full md:w-1/2 bg-green`}` the rendered css is calculating the width to be 0.25rem instead of '50%' 

I've also tried using an escape character like this:
` ${tw`w-full md:w-1\/2 bg-green`}`

**Comment by jlengstorf** [comment]
@Praneeth-Pike this is just a demo, so this issue is more likely to get solved upstream (either in Tailwind or in https://github.com/bradlc/babel-plugin-tailwind-components).

I'm going to close this since it can't be fixed in this demo without upstream changes. Thanks!
